// Code generated by protoc-gen-go. DO NOT EDIT.
// source: honeybadgerbft.proto

package orderer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HoneyBadgerBFTMessage is a wrapper type for the messages
// that the Kafka-based orderer deals with.
type HoneyBadgerBFTMessage struct {
	Sender               uint64                                    `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver             uint64                                    `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	ChainId              string                                    `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height               uint64                                    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Instance             uint64                                    `protobuf:"varint,5,opt,name=instance,proto3" json:"instance,omitempty"`
	New_Height           *HoneyBadgerBFTMessageNewHeight           `protobuf:"bytes,6,opt,name=new_Height,json=newHeight,proto3" json:"new_Height,omitempty"`
	CommonCoin           *HoneyBadgerBFTMessageCommonCoin          `protobuf:"bytes,7,opt,name=common_coin,json=commonCoin,proto3" json:"common_coin,omitempty"`
	BinaryAgreement      *HoneyBadgerBFTMessageBinaryAgreement     `protobuf:"bytes,8,opt,name=binary_agreement,json=binaryAgreement,proto3" json:"binary_agreement,omitempty"`
	ReliableBroadcast    *HoneyBadgerBFTMessageReliableBroadcast   `protobuf:"bytes,9,opt,name=reliable_broadcast,json=reliableBroadcast,proto3" json:"reliable_broadcast,omitempty"`
	ThresholdEncryption  *HoneyBadgerBFTMessageThresholdEncryption `protobuf:"bytes,10,opt,name=threshold_encryption,json=thresholdEncryption,proto3" json:"threshold_encryption,omitempty"`
	RequireBlock         *HoneyBadgerBFTMessageRequireBlock        `protobuf:"bytes,11,opt,name=require_block,json=requireBlock,proto3" json:"require_block,omitempty"`
	ResponseBlock        *HoneyBadgerBFTMessageResponseBlock       `protobuf:"bytes,12,opt,name=response_block,json=responseBlock,proto3" json:"response_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *HoneyBadgerBFTMessage) Reset()         { *m = HoneyBadgerBFTMessage{} }
func (m *HoneyBadgerBFTMessage) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessage) ProtoMessage()    {}
func (*HoneyBadgerBFTMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{0}
}

func (m *HoneyBadgerBFTMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessage.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessage.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessage.Merge(m, src)
}
func (m *HoneyBadgerBFTMessage) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessage.Size(m)
}
func (m *HoneyBadgerBFTMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessage proto.InternalMessageInfo

func (m *HoneyBadgerBFTMessage) GetSender() uint64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *HoneyBadgerBFTMessage) GetReceiver() uint64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *HoneyBadgerBFTMessage) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *HoneyBadgerBFTMessage) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HoneyBadgerBFTMessage) GetInstance() uint64 {
	if m != nil {
		return m.Instance
	}
	return 0
}

func (m *HoneyBadgerBFTMessage) GetNew_Height() *HoneyBadgerBFTMessageNewHeight {
	if m != nil {
		return m.New_Height
	}
	return nil
}

func (m *HoneyBadgerBFTMessage) GetCommonCoin() *HoneyBadgerBFTMessageCommonCoin {
	if m != nil {
		return m.CommonCoin
	}
	return nil
}

func (m *HoneyBadgerBFTMessage) GetBinaryAgreement() *HoneyBadgerBFTMessageBinaryAgreement {
	if m != nil {
		return m.BinaryAgreement
	}
	return nil
}

func (m *HoneyBadgerBFTMessage) GetReliableBroadcast() *HoneyBadgerBFTMessageReliableBroadcast {
	if m != nil {
		return m.ReliableBroadcast
	}
	return nil
}

func (m *HoneyBadgerBFTMessage) GetThresholdEncryption() *HoneyBadgerBFTMessageThresholdEncryption {
	if m != nil {
		return m.ThresholdEncryption
	}
	return nil
}

func (m *HoneyBadgerBFTMessage) GetRequireBlock() *HoneyBadgerBFTMessageRequireBlock {
	if m != nil {
		return m.RequireBlock
	}
	return nil
}

func (m *HoneyBadgerBFTMessage) GetResponseBlock() *HoneyBadgerBFTMessageResponseBlock {
	if m != nil {
		return m.ResponseBlock
	}
	return nil
}

type HoneyBadgerBFTMessageNewHeight struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageNewHeight) Reset()         { *m = HoneyBadgerBFTMessageNewHeight{} }
func (m *HoneyBadgerBFTMessageNewHeight) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageNewHeight) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageNewHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{1}
}

func (m *HoneyBadgerBFTMessageNewHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageNewHeight.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageNewHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageNewHeight.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageNewHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageNewHeight.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageNewHeight) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageNewHeight.Size(m)
}
func (m *HoneyBadgerBFTMessageNewHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageNewHeight.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageNewHeight proto.InternalMessageInfo

type HoneyBadgerBFTMessageCommonCoin struct {
	Round                uint64   `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageCommonCoin) Reset()         { *m = HoneyBadgerBFTMessageCommonCoin{} }
func (m *HoneyBadgerBFTMessageCommonCoin) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageCommonCoin) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageCommonCoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{2}
}

func (m *HoneyBadgerBFTMessageCommonCoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageCommonCoin.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageCommonCoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageCommonCoin.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageCommonCoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageCommonCoin.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageCommonCoin) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageCommonCoin.Size(m)
}
func (m *HoneyBadgerBFTMessageCommonCoin) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageCommonCoin.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageCommonCoin proto.InternalMessageInfo

func (m *HoneyBadgerBFTMessageCommonCoin) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *HoneyBadgerBFTMessageCommonCoin) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HoneyBadgerBFTMessageBinaryAgreement struct {
	Est                  *HoneyBadgerBFTMessageBinaryAgreementEST `protobuf:"bytes,1,opt,name=est,proto3" json:"est,omitempty"`
	Aux                  *HoneyBadgerBFTMessageBinaryAgreementAUX `protobuf:"bytes,2,opt,name=aux,proto3" json:"aux,omitempty"`
	Round                uint64                                   `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Value                bool                                     `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *HoneyBadgerBFTMessageBinaryAgreement) Reset()         { *m = HoneyBadgerBFTMessageBinaryAgreement{} }
func (m *HoneyBadgerBFTMessageBinaryAgreement) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageBinaryAgreement) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageBinaryAgreement) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{3}
}

func (m *HoneyBadgerBFTMessageBinaryAgreement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreement.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageBinaryAgreement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreement.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageBinaryAgreement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreement.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageBinaryAgreement) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreement.Size(m)
}
func (m *HoneyBadgerBFTMessageBinaryAgreement) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreement.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreement proto.InternalMessageInfo

func (m *HoneyBadgerBFTMessageBinaryAgreement) GetEst() *HoneyBadgerBFTMessageBinaryAgreementEST {
	if m != nil {
		return m.Est
	}
	return nil
}

func (m *HoneyBadgerBFTMessageBinaryAgreement) GetAux() *HoneyBadgerBFTMessageBinaryAgreementAUX {
	if m != nil {
		return m.Aux
	}
	return nil
}

func (m *HoneyBadgerBFTMessageBinaryAgreement) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *HoneyBadgerBFTMessageBinaryAgreement) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type HoneyBadgerBFTMessageBinaryAgreementEST struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageBinaryAgreementEST) Reset() {
	*m = HoneyBadgerBFTMessageBinaryAgreementEST{}
}
func (m *HoneyBadgerBFTMessageBinaryAgreementEST) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageBinaryAgreementEST) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageBinaryAgreementEST) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{4}
}

func (m *HoneyBadgerBFTMessageBinaryAgreementEST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementEST.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementEST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementEST.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementEST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementEST.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementEST) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementEST.Size(m)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementEST) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementEST.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementEST proto.InternalMessageInfo

type HoneyBadgerBFTMessageBinaryAgreementAUX struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageBinaryAgreementAUX) Reset() {
	*m = HoneyBadgerBFTMessageBinaryAgreementAUX{}
}
func (m *HoneyBadgerBFTMessageBinaryAgreementAUX) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageBinaryAgreementAUX) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageBinaryAgreementAUX) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{5}
}

func (m *HoneyBadgerBFTMessageBinaryAgreementAUX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementAUX.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementAUX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementAUX.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementAUX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementAUX.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementAUX) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementAUX.Size(m)
}
func (m *HoneyBadgerBFTMessageBinaryAgreementAUX) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementAUX.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageBinaryAgreementAUX proto.InternalMessageInfo

type HoneyBadgerBFTMessageReliableBroadcast struct {
	Val                  *HoneyBadgerBFTMessageReliableBroadcastVAL   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Echo                 *HoneyBadgerBFTMessageReliableBroadcastECHO  `protobuf:"bytes,2,opt,name=echo,proto3" json:"echo,omitempty"`
	Ready                *HoneyBadgerBFTMessageReliableBroadcastREADY `protobuf:"bytes,3,opt,name=ready,proto3" json:"ready,omitempty"`
	PadLength            uint64                                       `protobuf:"varint,4,opt,name=pad_length,json=padLength,proto3" json:"pad_length,omitempty"`
	Block                []byte                                       `protobuf:"bytes,5,opt,name=block,proto3" json:"block,omitempty"`
	RootHash             []byte                                       `protobuf:"bytes,6,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	Branch               [][]byte                                     `protobuf:"bytes,7,rep,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) Reset() {
	*m = HoneyBadgerBFTMessageReliableBroadcast{}
}
func (m *HoneyBadgerBFTMessageReliableBroadcast) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageReliableBroadcast) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageReliableBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{6}
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcast.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageReliableBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcast.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageReliableBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcast.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageReliableBroadcast) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcast.Size(m)
}
func (m *HoneyBadgerBFTMessageReliableBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcast proto.InternalMessageInfo

func (m *HoneyBadgerBFTMessageReliableBroadcast) GetVal() *HoneyBadgerBFTMessageReliableBroadcastVAL {
	if m != nil {
		return m.Val
	}
	return nil
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) GetEcho() *HoneyBadgerBFTMessageReliableBroadcastECHO {
	if m != nil {
		return m.Echo
	}
	return nil
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) GetReady() *HoneyBadgerBFTMessageReliableBroadcastREADY {
	if m != nil {
		return m.Ready
	}
	return nil
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) GetPadLength() uint64 {
	if m != nil {
		return m.PadLength
	}
	return 0
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *HoneyBadgerBFTMessageReliableBroadcast) GetBranch() [][]byte {
	if m != nil {
		return m.Branch
	}
	return nil
}

type HoneyBadgerBFTMessageReliableBroadcastVAL struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageReliableBroadcastVAL) Reset() {
	*m = HoneyBadgerBFTMessageReliableBroadcastVAL{}
}
func (m *HoneyBadgerBFTMessageReliableBroadcastVAL) String() string {
	return proto.CompactTextString(m)
}
func (*HoneyBadgerBFTMessageReliableBroadcastVAL) ProtoMessage() {}
func (*HoneyBadgerBFTMessageReliableBroadcastVAL) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{7}
}

func (m *HoneyBadgerBFTMessageReliableBroadcastVAL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastVAL.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastVAL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastVAL.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastVAL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastVAL.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastVAL) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastVAL.Size(m)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastVAL) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastVAL.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastVAL proto.InternalMessageInfo

type HoneyBadgerBFTMessageReliableBroadcastECHO struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageReliableBroadcastECHO) Reset() {
	*m = HoneyBadgerBFTMessageReliableBroadcastECHO{}
}
func (m *HoneyBadgerBFTMessageReliableBroadcastECHO) String() string {
	return proto.CompactTextString(m)
}
func (*HoneyBadgerBFTMessageReliableBroadcastECHO) ProtoMessage() {}
func (*HoneyBadgerBFTMessageReliableBroadcastECHO) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{8}
}

func (m *HoneyBadgerBFTMessageReliableBroadcastECHO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastECHO.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastECHO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastECHO.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastECHO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastECHO.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastECHO) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastECHO.Size(m)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastECHO) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastECHO.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastECHO proto.InternalMessageInfo

type HoneyBadgerBFTMessageReliableBroadcastREADY struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageReliableBroadcastREADY) Reset() {
	*m = HoneyBadgerBFTMessageReliableBroadcastREADY{}
}
func (m *HoneyBadgerBFTMessageReliableBroadcastREADY) String() string {
	return proto.CompactTextString(m)
}
func (*HoneyBadgerBFTMessageReliableBroadcastREADY) ProtoMessage() {}
func (*HoneyBadgerBFTMessageReliableBroadcastREADY) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{9}
}

func (m *HoneyBadgerBFTMessageReliableBroadcastREADY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastREADY.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastREADY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastREADY.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastREADY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastREADY.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastREADY) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastREADY.Size(m)
}
func (m *HoneyBadgerBFTMessageReliableBroadcastREADY) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastREADY.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageReliableBroadcastREADY proto.InternalMessageInfo

type HoneyBadgerBFTMessageThresholdEncryption struct {
	Shares               []*HoneyBadgerBFTMessageThresholdEncryptionShare `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *HoneyBadgerBFTMessageThresholdEncryption) Reset() {
	*m = HoneyBadgerBFTMessageThresholdEncryption{}
}
func (m *HoneyBadgerBFTMessageThresholdEncryption) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageThresholdEncryption) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageThresholdEncryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{10}
}

func (m *HoneyBadgerBFTMessageThresholdEncryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryption.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageThresholdEncryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryption.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageThresholdEncryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryption.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageThresholdEncryption) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryption.Size(m)
}
func (m *HoneyBadgerBFTMessageThresholdEncryption) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryption.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryption proto.InternalMessageInfo

func (m *HoneyBadgerBFTMessageThresholdEncryption) GetShares() []*HoneyBadgerBFTMessageThresholdEncryptionShare {
	if m != nil {
		return m.Shares
	}
	return nil
}

type HoneyBadgerBFTMessageThresholdEncryptionShare struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) Reset() {
	*m = HoneyBadgerBFTMessageThresholdEncryptionShare{}
}
func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) String() string {
	return proto.CompactTextString(m)
}
func (*HoneyBadgerBFTMessageThresholdEncryptionShare) ProtoMessage() {}
func (*HoneyBadgerBFTMessageThresholdEncryptionShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{11}
}

func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryptionShare.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryptionShare.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryptionShare.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryptionShare.Size(m)
}
func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryptionShare.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageThresholdEncryptionShare proto.InternalMessageInfo

func (m *HoneyBadgerBFTMessageThresholdEncryptionShare) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type HoneyBadgerBFTMessageRequireBlock struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageRequireBlock) Reset()         { *m = HoneyBadgerBFTMessageRequireBlock{} }
func (m *HoneyBadgerBFTMessageRequireBlock) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageRequireBlock) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageRequireBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{12}
}

func (m *HoneyBadgerBFTMessageRequireBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageRequireBlock.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageRequireBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageRequireBlock.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageRequireBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageRequireBlock.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageRequireBlock) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageRequireBlock.Size(m)
}
func (m *HoneyBadgerBFTMessageRequireBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageRequireBlock.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageRequireBlock proto.InternalMessageInfo

type HoneyBadgerBFTMessageResponseBlock struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HoneyBadgerBFTMessageResponseBlock) Reset()         { *m = HoneyBadgerBFTMessageResponseBlock{} }
func (m *HoneyBadgerBFTMessageResponseBlock) String() string { return proto.CompactTextString(m) }
func (*HoneyBadgerBFTMessageResponseBlock) ProtoMessage()    {}
func (*HoneyBadgerBFTMessageResponseBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_02b2ba828be87978, []int{13}
}

func (m *HoneyBadgerBFTMessageResponseBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HoneyBadgerBFTMessageResponseBlock.Unmarshal(m, b)
}
func (m *HoneyBadgerBFTMessageResponseBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HoneyBadgerBFTMessageResponseBlock.Marshal(b, m, deterministic)
}
func (m *HoneyBadgerBFTMessageResponseBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoneyBadgerBFTMessageResponseBlock.Merge(m, src)
}
func (m *HoneyBadgerBFTMessageResponseBlock) XXX_Size() int {
	return xxx_messageInfo_HoneyBadgerBFTMessageResponseBlock.Size(m)
}
func (m *HoneyBadgerBFTMessageResponseBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_HoneyBadgerBFTMessageResponseBlock.DiscardUnknown(m)
}

var xxx_messageInfo_HoneyBadgerBFTMessageResponseBlock proto.InternalMessageInfo

func (m *HoneyBadgerBFTMessageResponseBlock) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*HoneyBadgerBFTMessage)(nil), "orderer.HoneyBadgerBFTMessage")
	proto.RegisterType((*HoneyBadgerBFTMessageNewHeight)(nil), "orderer.HoneyBadgerBFTMessageNewHeight")
	proto.RegisterType((*HoneyBadgerBFTMessageCommonCoin)(nil), "orderer.HoneyBadgerBFTMessageCommonCoin")
	proto.RegisterType((*HoneyBadgerBFTMessageBinaryAgreement)(nil), "orderer.HoneyBadgerBFTMessageBinaryAgreement")
	proto.RegisterType((*HoneyBadgerBFTMessageBinaryAgreementEST)(nil), "orderer.HoneyBadgerBFTMessageBinaryAgreementEST")
	proto.RegisterType((*HoneyBadgerBFTMessageBinaryAgreementAUX)(nil), "orderer.HoneyBadgerBFTMessageBinaryAgreementAUX")
	proto.RegisterType((*HoneyBadgerBFTMessageReliableBroadcast)(nil), "orderer.HoneyBadgerBFTMessageReliableBroadcast")
	proto.RegisterType((*HoneyBadgerBFTMessageReliableBroadcastVAL)(nil), "orderer.HoneyBadgerBFTMessageReliableBroadcastVAL")
	proto.RegisterType((*HoneyBadgerBFTMessageReliableBroadcastECHO)(nil), "orderer.HoneyBadgerBFTMessageReliableBroadcastECHO")
	proto.RegisterType((*HoneyBadgerBFTMessageReliableBroadcastREADY)(nil), "orderer.HoneyBadgerBFTMessageReliableBroadcastREADY")
	proto.RegisterType((*HoneyBadgerBFTMessageThresholdEncryption)(nil), "orderer.HoneyBadgerBFTMessageThresholdEncryption")
	proto.RegisterType((*HoneyBadgerBFTMessageThresholdEncryptionShare)(nil), "orderer.HoneyBadgerBFTMessageThresholdEncryptionShare")
	proto.RegisterType((*HoneyBadgerBFTMessageRequireBlock)(nil), "orderer.HoneyBadgerBFTMessageRequireBlock")
	proto.RegisterType((*HoneyBadgerBFTMessageResponseBlock)(nil), "orderer.HoneyBadgerBFTMessageResponseBlock")
}

func init() {
	proto.RegisterFile("honeybadgerbft.proto", fileDescriptor_02b2ba828be87978)
}

var fileDescriptor_02b2ba828be87978 = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x5d, 0x53, 0xd3, 0x4c,
	0x14, 0xc7, 0xa7, 0x94, 0xbe, 0x9d, 0x96, 0xe7, 0x65, 0x9f, 0x3e, 0x4e, 0xd4, 0x51, 0x6b, 0x7c,
	0xa1, 0x80, 0x54, 0x2c, 0x8e, 0x97, 0xce, 0xb4, 0x50, 0x2c, 0x0e, 0xc2, 0xb8, 0x80, 0x83, 0x5e,
	0x98, 0xd9, 0x24, 0x87, 0x26, 0x63, 0xd8, 0xad, 0xbb, 0x29, 0x58, 0x3f, 0xaa, 0xdf, 0xc1, 0x1b,
	0x3f, 0x81, 0x93, 0x4d, 0x82, 0xc5, 0x97, 0xb6, 0xb9, 0xcb, 0xff, 0x64, 0xff, 0xbf, 0xdd, 0x3d,
	0x39, 0xe7, 0x04, 0xea, 0x9e, 0xe0, 0x38, 0xb6, 0x99, 0x3b, 0x40, 0x69, 0x9f, 0x86, 0xad, 0xa1,
	0x14, 0xa1, 0x20, 0x25, 0x21, 0x5d, 0x94, 0x28, 0xcd, 0x6f, 0x05, 0xf8, 0xbf, 0x1f, 0xad, 0xe8,
	0xea, 0x15, 0xdd, 0x9d, 0xa3, 0x57, 0xa8, 0x14, 0x1b, 0x20, 0xb9, 0x06, 0x45, 0x85, 0xdc, 0x45,
	0x69, 0xe4, 0x1a, 0xb9, 0xe6, 0x22, 0x4d, 0x14, 0xb9, 0x01, 0x65, 0x89, 0x0e, 0xfa, 0xe7, 0x28,
	0x8d, 0x05, 0xfd, 0xe6, 0x52, 0x93, 0xeb, 0x50, 0x76, 0x3c, 0xe6, 0x73, 0xcb, 0x77, 0x8d, 0x7c,
	0x23, 0xd7, 0xac, 0xd0, 0x92, 0xd6, 0xbb, 0x6e, 0x84, 0xf3, 0xd0, 0x1f, 0x78, 0xa1, 0xb1, 0x18,
	0xe3, 0x62, 0x15, 0xe1, 0x7c, 0xae, 0x42, 0xc6, 0x1d, 0x34, 0x0a, 0x31, 0x2e, 0xd5, 0x64, 0x07,
	0x80, 0xe3, 0x85, 0xd5, 0x8f, 0x7d, 0xc5, 0x46, 0xae, 0x59, 0x6d, 0x2f, 0xb7, 0x92, 0xa3, 0xb7,
	0x7e, 0x7b, 0xec, 0x7d, 0xbc, 0x88, 0x97, 0xd3, 0x0a, 0x4f, 0x1f, 0xc9, 0x2e, 0x54, 0x1d, 0x71,
	0x76, 0x26, 0xb8, 0xe5, 0x08, 0x9f, 0x1b, 0x25, 0x0d, 0x6a, 0x4e, 0x07, 0x6d, 0x69, 0xc3, 0x96,
	0xf0, 0x39, 0x05, 0xe7, 0xf2, 0x99, 0x9c, 0xc0, 0x3f, 0xb6, 0xcf, 0x99, 0x1c, 0x5b, 0x6c, 0x20,
	0x11, 0xcf, 0x90, 0x87, 0x46, 0x59, 0xf3, 0xd6, 0xa7, 0xf3, 0xba, 0xda, 0xd5, 0x49, 0x4d, 0xf4,
	0x6f, 0xfb, 0x6a, 0x80, 0xbc, 0x07, 0x22, 0x31, 0xf0, 0x99, 0x1d, 0xa0, 0x65, 0x4b, 0xc1, 0x5c,
	0x87, 0xa9, 0xd0, 0xa8, 0x68, 0xf6, 0xe3, 0xe9, 0x6c, 0x9a, 0xf8, 0xba, 0xa9, 0x8d, 0xfe, 0x2b,
	0x7f, 0x0e, 0x11, 0x17, 0xea, 0xa1, 0x27, 0x51, 0x79, 0x22, 0x70, 0x2d, 0xe4, 0x8e, 0x1c, 0x0f,
	0x43, 0x5f, 0x70, 0x03, 0xf4, 0x0e, 0x4f, 0xa6, 0xef, 0x70, 0x94, 0x3a, 0x7b, 0x97, 0x46, 0xfa,
	0x5f, 0xf8, 0x6b, 0x90, 0x1c, 0xc0, 0x92, 0xc4, 0x8f, 0x23, 0x5f, 0xa2, 0x65, 0x07, 0xc2, 0xf9,
	0x60, 0x54, 0x35, 0x7e, 0x75, 0xd6, 0x05, 0xb4, 0xa5, 0x1b, 0x39, 0x68, 0x4d, 0x4e, 0x28, 0x42,
	0xe1, 0x2f, 0x89, 0x6a, 0x28, 0xb8, 0x4a, 0x89, 0x35, 0x4d, 0x5c, 0x9b, 0x45, 0x8c, 0x3d, 0x31,
	0x72, 0x49, 0x4e, 0x4a, 0xb3, 0x01, 0xb7, 0xa7, 0x17, 0x8f, 0xf9, 0x1a, 0xee, 0xcc, 0xa8, 0x0a,
	0x52, 0x87, 0x82, 0x14, 0x23, 0xee, 0x26, 0xed, 0x11, 0x0b, 0x62, 0x40, 0x69, 0xc8, 0xc6, 0x81,
	0x60, 0xae, 0x6e, 0x8e, 0x1a, 0x4d, 0xa5, 0xf9, 0x25, 0x07, 0xf7, 0xe7, 0xa9, 0x0c, 0xd2, 0x85,
	0x3c, 0xaa, 0x50, 0x63, 0xab, 0xed, 0x8d, 0x4c, 0x55, 0xd5, 0x3b, 0x3c, 0xa2, 0x91, 0x39, 0x62,
	0xb0, 0xd1, 0x27, 0x7d, 0x84, 0xac, 0x8c, 0xce, 0xf1, 0x09, 0x8d, 0xcc, 0x3f, 0x2e, 0x98, 0x9f,
	0xbc, 0x60, 0x1d, 0x0a, 0xe7, 0x2c, 0x18, 0xa1, 0x6e, 0xe3, 0x32, 0x8d, 0x85, 0xb9, 0x02, 0xcb,
	0x73, 0x9e, 0x6f, 0xde, 0xa5, 0x9d, 0xe3, 0x13, 0xf3, 0xeb, 0x02, 0x3c, 0x9c, 0xaf, 0xe0, 0xc9,
	0x36, 0xe4, 0xcf, 0x59, 0x90, 0x24, 0xad, 0x9d, 0xb1, 0x5d, 0xde, 0x74, 0xf6, 0x68, 0x64, 0x27,
	0x2f, 0x60, 0x11, 0x1d, 0x4f, 0x24, 0x79, 0xdb, 0xcc, 0x88, 0xe9, 0x6d, 0xf5, 0x0f, 0xa8, 0x06,
	0x90, 0x97, 0x50, 0x90, 0xc8, 0xdc, 0xb1, 0xce, 0x5d, 0xb5, 0xfd, 0x34, 0x6b, 0xff, 0xf6, 0x3a,
	0xdb, 0x6f, 0x69, 0x8c, 0x20, 0xb7, 0x00, 0x86, 0xcc, 0xb5, 0x02, 0xe4, 0x83, 0xd0, 0x4b, 0xa6,
	0x67, 0x65, 0xc8, 0xdc, 0x3d, 0x1d, 0x88, 0x3e, 0x48, 0xdc, 0x17, 0x05, 0x5d, 0x6f, 0xb1, 0x20,
	0x37, 0xa1, 0x22, 0x85, 0x08, 0x2d, 0x8f, 0x29, 0x4f, 0x4f, 0xce, 0x1a, 0x2d, 0x47, 0x81, 0x3e,
	0x53, 0x5e, 0x34, 0x8b, 0x6d, 0xc9, 0xb8, 0xe3, 0x19, 0xa5, 0x46, 0xbe, 0x59, 0xa3, 0x89, 0x32,
	0xd7, 0x60, 0x65, 0xee, 0x84, 0x99, 0x8f, 0x60, 0x75, 0xfe, 0xb4, 0x98, 0xeb, 0xb0, 0x96, 0xe1,
	0xea, 0xe6, 0x67, 0x68, 0xce, 0x3b, 0x87, 0xc8, 0x3e, 0x14, 0x95, 0xc7, 0x24, 0x2a, 0x23, 0xd7,
	0xc8, 0x37, 0xab, 0xed, 0x67, 0x99, 0x47, 0xd9, 0x61, 0x64, 0xa7, 0x09, 0xc5, 0xdc, 0x85, 0xf5,
	0x4c, 0xc6, 0xc9, 0x9e, 0xcf, 0x5d, 0xed, 0xf9, 0x7b, 0x70, 0x77, 0xe6, 0xbc, 0x33, 0x9f, 0x83,
	0x39, 0x7b, 0x84, 0xfd, 0x79, 0x93, 0xee, 0x06, 0x3c, 0x10, 0x72, 0xd0, 0xf2, 0xc6, 0x43, 0x94,
	0x01, 0x46, 0x8c, 0xd6, 0x29, 0xb3, 0xa5, 0xef, 0xc4, 0xff, 0x7a, 0x95, 0xa6, 0xe3, 0x5d, 0xfa,
	0xd3, 0xb7, 0x8b, 0xfa, 0xc5, 0xe6, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x2c, 0x2b, 0xbe,
	0x1c, 0x08, 0x00, 0x00,
}
